//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescriptionOfGood
    {
        public int DescriptionOfGoodsId { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int DepartureTypeId { get; set; }
        public int TariffsViewId { get; set; }
        public decimal Weight { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual DepartureType DepartureType { get; set; }
        public virtual TariffsView TariffsView { get; set; }
    }
}
