//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescriptionOfGood
    {
        public int DescriptionOfGoodsId { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int DepartureTypeId { get; set; }
        public int TariffsViewId { get; set; }
        public decimal Weight { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual DepartureType DepartureType { get; set; }
        public virtual TariffsView TariffsView { get; set; }
    }
}
