//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using MVC_validation_on_server.Attributes;

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Collections.Generic;
    [FeedBack]
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public int MessageThemeId { get; set; }
        [Required]
        public string Question { get; set; }

        public virtual MessageTheme MessageTheme { get; set; }
    }
}
