//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sender
    {
        public int SenderId { get; set; }
        public string BIN_IIN { get; set; }
        public string ContactPerson { get; set; }
        public string SendersAddress { get; set; }
        public string Email { get; set; }
        public System.DateTime DesirableDate { get; set; }
        public System.TimeSpan WhenPickUpShipment { get; set; }
        public int FormOfPaymentId { get; set; }
    
        public virtual FormOfPayment FormOfPayment { get; set; }
    }
}
