//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sender
    {
        public int SenderId { get; set; }
        public string BIN_IIN { get; set; }
        public string ContactPerson { get; set; }
        public string SendersAddress { get; set; }
        public string Email { get; set; }
        public System.DateTime DesirableDate { get; set; }
        public System.TimeSpan WhenPickUpShipment { get; set; }
        public int FormOfPaymentId { get; set; }
    
        public virtual FormOfPayment FormOfPayment { get; set; }
    }
}
