//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_validation_on_server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerValidation_DbEntities : DbContext
    {
        public ServerValidation_DbEntities()
            : base("name=ServerValidation_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<MessageTheme> MessageThemes { get; set; }
        public virtual DbSet<FormOfPayment> FormOfPayments { get; set; }
        public virtual DbSet<Sender> Senders { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DepartureType> DepartureTypes { get; set; }
        public virtual DbSet<DescriptionOfGood> DescriptionOfGoods { get; set; }
        public virtual DbSet<TariffsView> TariffsViews { get; set; }
        public virtual DbSet<CallingCourier> CallingCouriers { get; set; }
    }
}
